import { ProvenanceWork, AssociatedProduct } from './types'

export const INITIAL_PROVENANCE_WORKS: ProvenanceWork[] = [
  {
    id: 'work-rainforest-diffuser',
    name: 'Rainforest Diffuser',
    subtitle: '天然雨林生态水晶扩香仪产品设计稿',
    coverImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=80',
    ],
    type: '产品设计',
    owner: 'Luna Studio',
    createdAt: '2026 年 8 月 24 日',
    code: 'ORG-8F3A-91CD',
    status: 'verified',
    description: '采用整块光学级水晶与天然火山岩构筑的冷香散发结构，兼具声学共振与微孔毛细导油系统。',
    fingerprint: {
      algorithm: 'SHA-256',
      hash: '8f3a92b4...91cd',
      fullHash: '8f3a92b4e82c19a0f44bcde710e24177d483b3819c90b6a2f190e2991cda289',
      status: '已验证',
      onChainRecorded: '已存在',
    },
    timeline: [
      {
        id: 't1',
        title: '创建作品',
        actorOrDesc: 'Luna Studio',
        date: '2026 年 8 月 24 日',
        status: 'completed',
      },
      {
        id: 't2',
        title: '提交审核',
        actorOrDesc: '来源审核',
        date: '2026 年 8 月 24 日',
        status: 'completed',
      },
      {
        id: 't3',
        title: '来源验证',
        actorOrDesc: '原创作品',
        date: '2026 年 8 月 25 日',
        status: 'completed',
      },
      {
        id: 't4',
        title: '数字存证',
        actorOrDesc: '作品指纹已生成',
        date: '2026 年 8 月 25 日',
        status: 'completed',
      },
      {
        id: 't5',
        title: '平台保护',
        actorOrDesc: 'Omnilink 网络保护 · 已开启',
        date: '2026 年 8 月 25 日',
        status: 'completed',
      },
    ],
    associatedProducts: [
      {
        id: 'prod-rf-001',
        name: 'Rainforest Crystal Diffuser',
        sku: 'RF-001',
        image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 899,
        category: '家居香氛',
      },
      {
        id: 'prod-rf-002',
        name: 'Rainforest Gift Set',
        sku: 'RF-002',
        image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 1399,
        category: '礼品套装',
      },
      {
        id: 'prod-rf-003',
        name: 'Rainforest Mini',
        sku: 'RF-003',
        image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80',
        status: 'draft',
        price: 499,
        category: '便携随身',
      },
      {
        id: 'prod-rf-004',
        name: 'Rainforest Refill Oil 50ml',
        sku: 'RF-004',
        image: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 260,
        category: '精油补充装',
      },
    ],
    authorizedMerchants: [
      {
        id: 'auth-1',
        name: 'ABC Studio',
        scope: '商品展示',
        validity: '2026.08.24 — 2027.08.24',
        status: 'active',
        authorizedDate: '2026-08-24',
      },
      {
        id: 'auth-2',
        name: 'XYZ Studio',
        scope: '营销内容',
        validity: '长期',
        status: 'active',
        authorizedDate: '2026-08-25',
      },
    ],
    platformProtection: {
      status: 'protected',
      protectedProductCount: 4,
      matchRecordCount: 6,
      unauthorizedUsageCount: 0,
      recentDetections: [
        {
          id: 'det-1',
          storeName: 'ABC Store',
          matchRate: 98,
          status: 'authorized',
          timeAgo: '昨天',
          matchedItemName: 'Rainforest Diffuser (Storefront Banner)',
        },
        {
          id: 'det-2',
          storeName: 'XYZ Store',
          matchRate: 94,
          status: 'unauthorized',
          timeAgo: '2 小时前',
          matchedItemName: '未授权商品主图上传尝试 (已成功拦截)',
        },
      ],
    },
  },
  {
    id: 'work-eternal-time-packaging',
    name: 'Eternal Time Packaging',
    subtitle: '恒时系列极简几何结构外装设计',
    coverImage: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80',
    type: '包装设计',
    owner: 'Luna Studio',
    createdAt: '2026 年 8 月 27 日',
    code: 'ORG-2B44-77EA',
    status: 'reviewing',
    description: '采用 100% 环保无塑压制纤维与磁吸折叠结构，表面覆有微触感亚光纹理。',
    reviewProgress: {
      submitted: true,
      originReviewed: true,
      originalityReview: 'in_progress',
      fingerprintGenerated: false,
      platformProtected: false,
      submissionDate: '2026 年 8 月 27 日',
      priority: '较高',
    },
    fingerprint: {
      algorithm: 'SHA-256',
      hash: '2b4477...ea19',
      fullHash: '2b4477ea19c8f0029b93405df621a6a9b4009211c47a95089e17b88fa53890ce',
      status: '生成中',
      onChainRecorded: '待同步',
    },
    timeline: [
      {
        id: 't2-1',
        title: '已提交',
        actorOrDesc: 'Luna Studio · 来源提报',
        date: '2026 年 8 月 27 日',
        status: 'completed',
      },
      {
        id: 't2-2',
        title: '来源审核',
        actorOrDesc: '原始工程文件校验完成',
        date: '2026 年 8 月 27 日',
        status: 'completed',
      },
      {
        id: 't2-3',
        title: '原创性审核',
        actorOrDesc: '平台正在比对全网视觉特征',
        date: '进行中',
        status: 'current',
      },
      {
        id: 't2-4',
        title: '数字存证',
        actorOrDesc: '等待原创审核完成',
        date: '等待完成',
        status: 'upcoming',
      },
      {
        id: 't2-5',
        title: '平台保护',
        actorOrDesc: 'Omnilink 网络保护',
        date: '等待开启',
        status: 'upcoming',
      },
    ],
    associatedProducts: [
      {
        id: 'prod-et-001',
        name: 'Eternal Time Luxury Box Set',
        sku: 'ET-BOX-01',
        image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 1880,
        category: '包装定制',
      },
      {
        id: 'prod-et-002',
        name: 'Eternal Time Refill Sleeve',
        sku: 'ET-SLV-02',
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80',
        status: 'draft',
        price: 320,
        category: '配件外盒',
      },
    ],
    authorizedMerchants: [
      {
        id: 'auth-et-1',
        name: 'Nordic Essence Co.',
        scope: '全渠道商品包装',
        validity: '2026.09.01 — 2027.09.01',
        status: 'pending',
        authorizedDate: '2026-08-27',
      },
    ],
    platformProtection: {
      status: 'pending',
      protectedProductCount: 2,
      matchRecordCount: 0,
      unauthorizedUsageCount: 0,
      recentDetections: [],
    },
  },
  {
    id: 'work-crystal-sculpture-01',
    name: 'Crystal Sculpture No.01',
    subtitle: '手工热熔吹制高透光学透镜系列',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    type: '产品设计',
    owner: 'Luna Studio',
    createdAt: '2026 年 8 月 26 日',
    code: 'ORG-9C11-00F3',
    status: 'pending',
    description: '非对称双曲面晶体雕塑造型，专为现代室内微光氛围照明设计。',
    fingerprint: {
      algorithm: 'SHA-256',
      hash: '9c1100...f38b',
      fullHash: '9c1100f38b812a01f7823e449a0d817454238e8a1567bc8d91012903741890e1',
      status: '待验证',
      onChainRecorded: '待同步',
    },
    timeline: [
      {
        id: 't3-1',
        title: '创建作品',
        actorOrDesc: 'Luna Studio · 草稿存证',
        date: '2026 年 8 月 26 日',
        status: 'completed',
      },
      {
        id: 't3-2',
        title: '提交审核',
        actorOrDesc: '待商家正式提报',
        date: '待提报',
        status: 'upcoming',
      },
    ],
    associatedProducts: [
      {
        id: 'prod-cs-001',
        name: 'Crystal Sculpture Ambient Light',
        sku: 'CS-LIGHT-01',
        image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
        status: 'draft',
        price: 2400,
        category: '艺术灯具',
      },
    ],
    authorizedMerchants: [],
    platformProtection: {
      status: 'pending',
      protectedProductCount: 1,
      matchRecordCount: 0,
      unauthorizedUsageCount: 0,
      recentDetections: [],
    },
  },
  {
    id: 'work-aura-luminary',
    name: 'Aura Luminary Series',
    subtitle: '无线磁悬浮环形光触控台灯',
    coverImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80',
    type: '产品设计',
    owner: 'Luna Studio',
    createdAt: '2026 年 7 月 15 日',
    code: 'ORG-992C-38A2',
    status: 'verified',
    description: '采用航天级阳极氧化铝与超导悬浮芯片，通过手势悬停调节色温与光通量。',
    fingerprint: {
      algorithm: 'SHA-256',
      hash: '992c38...a210',
      fullHash: '992c38a210ff4802c38827e8d00921b772183e9a1120ab58804918e9021cd5e3',
      status: '已验证',
      onChainRecorded: '已存在',
    },
    timeline: [
      {
        id: 't4-1',
        title: '创建作品',
        actorOrDesc: 'Luna Studio',
        date: '2026 年 7 月 15 日',
        status: 'completed',
      },
      {
        id: 't4-2',
        title: '来源验证',
        actorOrDesc: '原创工程数据验证完成',
        date: '2026 年 7 月 16 日',
        status: 'completed',
      },
      {
        id: 't4-3',
        title: '数字存证',
        actorOrDesc: '指纹记录归档',
        date: '2026 年 7 月 16 日',
        status: 'completed',
      },
      {
        id: 't4-4',
        title: '平台保护',
        actorOrDesc: 'Omnilink 网络全域监测中',
        date: '2026 年 7 月 16 日',
        status: 'completed',
      },
    ],
    associatedProducts: [
      {
        id: 'prod-al-001',
        name: 'Aura Luminary Desk Lamp (Matte Black)',
        sku: 'AL-BLK-01',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 1599,
        category: '智能灯具',
      },
      {
        id: 'prod-al-002',
        name: 'Aura Luminary Desk Lamp (Silver Edition)',
        sku: 'AL-SLV-02',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 1699,
        category: '智能灯具',
      },
    ],
    authorizedMerchants: [
      {
        id: 'auth-al-1',
        name: 'DesignRepublic',
        scope: '全渠道分销与展示',
        validity: '2026.07.16 — 2028.07.16',
        status: 'active',
      },
      {
        id: 'auth-al-2',
        name: 'MOMA Store APAC',
        scope: '线下展厅与精选陈列',
        validity: '长期',
        status: 'active',
      },
    ],
    platformProtection: {
      status: 'protected',
      protectedProductCount: 6,
      matchRecordCount: 14,
      unauthorizedUsageCount: 0,
      recentDetections: [
        {
          id: 'det-al-1',
          storeName: 'DesignRepublic Global',
          matchRate: 100,
          status: 'authorized',
          timeAgo: '3 天前',
        },
      ],
    },
  },
  {
    id: 'work-monolith-sound',
    name: 'Monolith Sound Identity',
    subtitle: '一体化阳极铝雕刻立体声声学外形',
    coverImage: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80',
    type: '品牌素材',
    owner: 'Luna Studio',
    createdAt: '2026 年 6 月 10 日',
    code: 'ORG-77B1-4040',
    status: 'verified',
    description: '重力铸造实心铝基底配合蜂窝多孔声学导流面罩，为 Omnilink 音频系列核心视觉资产。',
    fingerprint: {
      algorithm: 'SHA-256',
      hash: '77b140...40ea',
      fullHash: '77b14040ead20311f993910c01a88b4382910cd0448102a9018471900192e881',
      status: '已验证',
      onChainRecorded: '已存在',
    },
    timeline: [
      {
        id: 't5-1',
        title: '创建作品',
        actorOrDesc: 'Luna Studio',
        date: '2026 年 6 月 10 日',
        status: 'completed',
      },
      {
        id: 't5-2',
        title: '来源验证',
        actorOrDesc: '原创品牌视觉资产确认',
        date: '2026 年 6 月 11 日',
        status: 'completed',
      },
      {
        id: 't5-3',
        title: '数字存证',
        actorOrDesc: '全景声学外观存证已归档',
        date: '2026 年 6 月 11 日',
        status: 'completed',
      },
      {
        id: 't5-4',
        title: '平台保护',
        actorOrDesc: 'Omnilink 网络保护 · 已开启',
        date: '2026 年 6 月 11 日',
        status: 'completed',
      },
    ],
    associatedProducts: [
      {
        id: 'prod-ms-001',
        name: 'Monolith High-Fidelity Audio',
        sku: 'MS-HIFI-01',
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
        status: 'published',
        price: 3299,
        category: '高端音响',
      },
    ],
    authorizedMerchants: [
      {
        id: 'auth-ms-1',
        name: 'Acoustic Labs Japan',
        scope: '全渠道音响搭载展示',
        validity: '长期',
        status: 'active',
      },
    ],
    platformProtection: {
      status: 'protected',
      protectedProductCount: 3,
      matchRecordCount: 8,
      unauthorizedUsageCount: 0,
      recentDetections: [],
    },
  },
]

export const AVAILABLE_CATALOG_PRODUCTS: AssociatedProduct[] = [
  {
    id: 'prod-rf-001',
    name: 'Rainforest Crystal Diffuser',
    sku: 'RF-001',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 899,
    category: '家居香氛',
  },
  {
    id: 'prod-rf-002',
    name: 'Rainforest Gift Set',
    sku: 'RF-002',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 1399,
    category: '礼品套装',
  },
  {
    id: 'prod-rf-003',
    name: 'Rainforest Mini',
    sku: 'RF-003',
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80',
    status: 'draft',
    price: 499,
    category: '便携随身',
  },
  {
    id: 'prod-rf-004',
    name: 'Rainforest Refill Oil 50ml',
    sku: 'RF-004',
    image: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 260,
    category: '精油补充装',
  },
  {
    id: 'prod-et-001',
    name: 'Eternal Time Luxury Box Set',
    sku: 'ET-BOX-01',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 1880,
    category: '包装定制',
  },
  {
    id: 'prod-cs-001',
    name: 'Crystal Sculpture Ambient Light',
    sku: 'CS-LIGHT-01',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
    status: 'draft',
    price: 2400,
    category: '艺术灯具',
  },
  {
    id: 'prod-al-001',
    name: 'Aura Luminary Desk Lamp (Matte Black)',
    sku: 'AL-BLK-01',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 1599,
    category: '智能灯具',
  },
  {
    id: 'prod-al-002',
    name: 'Aura Luminary Desk Lamp (Silver Edition)',
    sku: 'AL-SLV-02',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80',
    status: 'published',
    price: 1699,
    category: '智能灯具',
  },
]
