import {
  KnowledgeBaseItem,
  KnowledgeSource,
  BrandBusinessStructuredData,
  ProductKnowledgeSupplementaryData,
  SupportPolicyStructuredData,
  MarketplacePackage,
  ResearchModel,
  KnowledgeFileSource,
  KnowledgeProductBinding,
  AiSuggestedBindingMatch,
} from './types'

export const SYSTEM_KNOWLEDGE_BASES: KnowledgeBaseItem[] = [
  {
    id: 'brand-business',
    title: '品牌与企业资料',
    titleEn: 'Brand & Business',
    description: '官方品牌形象、企业联系方式、社交矩阵与独立站全渠道官方资料',
    descriptionEn: 'Official brand identity, corporate profile, contact channels & social accounts.',
    icon: 'Sparkles',
    visibility: 'customer-facing',
    sourceCount: 5,
    storageUsed: '4.8 MB',
    lastSynced: '10 分钟前',
    activeConnections: ['Storefront', 'AI Chatbot', 'OpenAgent Gateway'],
    isSystem: true,
    sources: [
      {
        id: 'src-brand-1',
        name: 'Omnilink_Brand_Guidelines_2026.pdf',
        type: 'pdf',
        size: '2.4 MB',
        updatedAt: '2026-08-15',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 18450,
        summary: '品牌视觉识别系统、Slogan、色盘规范与品牌调性指引',
      },
      {
        id: 'src-brand-2',
        name: 'Company_Profile_Overview.md',
        type: 'markdown',
        size: '128 KB',
        updatedAt: '2026-08-18',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 4200,
        summary: '公司发展历程、创始团队背景与全球办事处信息',
      },
      {
        id: 'src-brand-3',
        name: 'Official_Social_Channels.json',
        type: 'structured',
        size: '42 KB',
        updatedAt: '2026-08-19',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 1200,
        summary: 'Twitter/X, Instagram, LinkedIn 及官方客服 WhatsApp 结构化映射',
      },
      {
        id: 'src-brand-4',
        name: 'Press_Kit_Executive_Bio.docx',
        type: 'docx',
        size: '1.2 MB',
        updatedAt: '2026-08-10',
        visibility: 'customer-facing',
        selected: false,
        tokensCount: 6500,
        summary: '媒体新闻稿件包与发言人口径',
      },
      {
        id: 'src-brand-5',
        name: 'https://omnilink.store/about',
        type: 'url',
        size: '1.0 MB',
        updatedAt: '2026-08-19',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 3800,
        summary: '官网实时 About 页面抓取镜像',
      },
    ],
  },
  {
    id: 'product-knowledge',
    title: '产品知识补充库',
    titleEn: 'Product Knowledge',
    description: '非主数据的产品深度知识：产品故事、使用教程、保养指南、认证标准与 AI 导购上下文',
    descriptionEn: 'Supplementary product intelligence: stories, usage guidelines, care instructions & AI context.',
    icon: 'FileText',
    visibility: 'customer-facing',
    sourceCount: 7,
    storageUsed: '8.1 MB',
    lastSynced: '25 分钟前',
    activeConnections: ['Storefront Detail View', 'Product Recommendation Agent'],
    isSystem: true,
    sources: [
      {
        id: 'src-prod-1',
        name: 'Acoustic_Architecture_DeepDive.pdf',
        type: 'pdf',
        size: '3.6 MB',
        updatedAt: '2026-08-14',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 24500,
        summary: '空间音频算法与主动降噪硬件声学架构白皮书',
      },
      {
        id: 'src-prod-2',
        name: 'Wearable_Care_Instructions_v2.md',
        type: 'markdown',
        size: '86 KB',
        updatedAt: '2026-08-17',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 3100,
        summary: '耳垫清洁、电池保养周期与防水注意事项',
      },
      {
        id: 'src-prod-3',
        name: 'Global_Compliance_Certificates.pdf',
        type: 'pdf',
        size: '2.1 MB',
        updatedAt: '2026-08-12',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 12000,
        summary: 'CE, FCC, RoHS, Bluetooth SIG 官方认证编号与检测报告',
      },
      {
        id: 'src-prod-4',
        name: 'Cross_Device_Compatibility_Matrix.md',
        type: 'markdown',
        size: '145 KB',
        updatedAt: '2026-08-18',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 5400,
        summary: 'iOS / Android / Windows / macOS 多设备无缝双连兼容性说明',
      },
      {
        id: 'src-prod-5',
        name: 'Product_Story_And_Design_Philosophy.md',
        type: 'markdown',
        size: '64 KB',
        updatedAt: '2026-08-16',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 2800,
        summary: '极简北欧工业美学设计理念与环保可回收包装故事',
      },
      {
        id: 'src-prod-6',
        name: 'Troubleshooting_Diagnostic_Tree.pdf',
        type: 'pdf',
        size: '1.8 MB',
        updatedAt: '2026-08-11',
        visibility: 'customer-facing',
        selected: false,
        tokensCount: 9200,
        summary: '蓝牙配对异常与固件升级失败排障决策树',
      },
      {
        id: 'src-prod-7',
        name: 'Supplementary_AI_Context.json',
        type: 'structured',
        size: '310 KB',
        updatedAt: '2026-08-19',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 8900,
        summary: '针对大模型导购推理的场景化语义触发词与适用人群画像',
      },
    ],
  },
  {
    id: 'support-policy',
    title: '客服与服务政策',
    titleEn: 'Support & Policy',
    description: 'FAQ 常见问答、全球物流时效、退换货政策、质保条款与客服响应 SLA',
    descriptionEn: 'Structured FAQs, global shipping rates, return windows, warranty terms & support SLAs.',
    icon: 'ShieldCheck',
    visibility: 'customer-facing',
    sourceCount: 4,
    storageUsed: '3.3 MB',
    lastSynced: '1 小时前',
    activeConnections: ['Storefront Footer', 'Customer Support Bot', 'WhatsApp Agent'],
    isSystem: true,
    sources: [
      {
        id: 'src-policy-1',
        name: 'Global_Shipping_And_Delivery_Policy_2026.md',
        type: 'markdown',
        size: '220 KB',
        updatedAt: '2026-08-18',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 7800,
        summary: 'DHL/FedEx 跨境履约时效、偏远地区附加费与包邮门槛说明',
      },
      {
        id: 'src-policy-2',
        name: 'Returns_And_Refund_Procedure.md',
        type: 'markdown',
        size: '180 KB',
        updatedAt: '2026-08-19',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 6200,
        summary: '30 天无忧退换货细则、商品外观完好要求及运费承担原则',
      },
      {
        id: 'src-policy-3',
        name: 'Warranty_Terms_2Year_Limited.pdf',
        type: 'pdf',
        size: '1.4 MB',
        updatedAt: '2026-08-05',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 8900,
        summary: '2 年官方有限保修责任范围、非保修意外损坏判定与售后维修网点',
      },
      {
        id: 'src-policy-4',
        name: 'Customer_Support_FAQ_Base.json',
        type: 'structured',
        size: '1.5 MB',
        updatedAt: '2026-08-19',
        visibility: 'customer-facing',
        selected: true,
        tokensCount: 22000,
        summary: '包含 68 条经过人工复核的高频买家咨询问答库',
      },
    ],
  },
]

export const INITIAL_BRAND_DATA: BrandBusinessStructuredData = {
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&h=120&auto=format&fit=crop&q=80',
  brandName: 'Omnilink Audio & Tech',
  storeDisplayName: 'Omnilink Flagship Store',
  contactPerson: 'Thomas Vance (Global Relations)',
  email: 'support@omnilink.store',
  phone: '+1 (800) 882-9102',
  whatsapp: '+1 (415) 992-0381',
  address: '770 Innovation Way, Suite 400, San Francisco, CA 94107, United States',
  consultationUrl: 'https://omnilink.store/consultation',
  socialChannels: {
    instagram: 'https://instagram.com/omnilink_tech',
    facebook: 'https://facebook.com/omnilinkstore',
    youtube: 'https://youtube.com/@omnilink_official',
    tiktok: 'https://tiktok.com/@omnilink_audio',
    twitter: 'https://x.com/omnilink_hq',
    linkedin: 'https://linkedin.com/company/omnilink-commerce',
  },
  officialLinks: {
    website: 'https://omnilink.store',
    documentation: 'https://docs.omnilink.store',
    blog: 'https://omnilink.store/journal',
  },
}

export const INITIAL_PRODUCT_KNOWLEDGE: ProductKnowledgeSupplementaryData = {
  productStory:
    '诞生于旧金山声学实验室，Omnilink 致力于用前沿计算声学与环境智能，重塑人与声音的交互体验。我们坚信极致的降噪不应牺牲音乐的动态呼吸感。',
  usageScenarios:
    '1. 跨国长途飞行与高铁差旅深度降噪；2. 开放式工位免打扰高专注办公；3. 沉浸式空间音频观影与高解析度无损音乐鉴赏；4. 城市通勤与夜跑透传通透模式。',
  careInstructions:
    '避免浸水或在暴雨中使用（支持 IPX4 生活防泼溅）。清洁耳罩时请使用微湿的无绒软布轻轻擦拭，切勿使用酒精或强腐蚀溶剂。建议每 3 个月进行一次电池满充循环维护。',
  certificationNotes:
    '已通过欧盟 CE (EN 62368-1)、美国 FCC Part 15 Class B、RoHS 2.0 环保指令以及 Bluetooth SIG 5.3 官方无损协议认证。电池组具备 UN38.3 航空安全运输认证。',
  compatibilityMatrix:
    '全面兼容 Apple iOS 14+ (支持空间音频动态头部追踪)、Android 11+ (LDAC & AAC 高清编解码)、Windows 11 及 macOS Sonoma。支持双设备 Multipoint 智能秒切。',
  additionalAiContext:
    '当顾客询问关于“重度近视戴眼镜是否夹头”时，AI 导购应主动强调耳罩采用记忆慢回弹蛋白皮与减压转轴设计，佩戴眼镜连续 6 小时无压迫感。',
}

export const INITIAL_SUPPORT_POLICY: SupportPolicyStructuredData = {
  faqs: [
    {
      id: 'faq-1',
      question: '下单后多久能发货？提供运单追踪吗？',
      answer: '现货订单在付款成功后 24 小时内发出（周末及法定节假日顺延至下一个工作日）。发货后系统会自动发送包含物流追踪号的邮件通知。',
      category: 'Shipping',
    },
    {
      id: 'faq-2',
      question: '支持多少天无理由退换货？需要承担运费吗？',
      answer: '我们提供自签收之日起 30 天无忧退换货保障。若因商品质量问题退货，由我司全额承担往返运费；若因个人喜好退换，需由买家承担回寄运费。',
      category: 'Returns',
    },
    {
      id: 'faq-3',
      question: '官方保修期限是多久？如何申请售后质保？',
      answer: '所有官方售出的硬件设备均享受 2 年全球有限保修。在保修期内如遇非人为硬件故障，可联系 support@omnilink.store 提供订单号即可申请寄修换新。',
      category: 'Warranty',
    },
    {
      id: 'faq-4',
      question: '耳机支持同时连接手机和电脑吗？',
      answer: '支持。搭载智能双设备多点连接（Multipoint）技术，电脑播放视频时若手机来电，音频流将自动无缝切换至手机通话。',
      category: 'Product',
    },
  ],
  shipping: {
    processingTime: '24 小时内闪电发货（工作日）',
    standardDelivery: '3 - 5 个工作日（标准陆运 / 航空快件）',
    expressDelivery: '次日达 / 2 个工作日（顺丰特快 / DHL Express）',
    freeShippingThreshold: '全场单笔订单满 ¥199 / $49 免运费',
    supportedCarriers: '顺丰速运 (SF Express), DHL, FedEx, USPS, 菜鸟跨境特快',
    internationalNotes: '跨境发货采用 DDP（完税交货）模式，买家无需在海关额外支付关税。',
  },
  returns: {
    returnWindowDays: 30,
    conditions: '商品外包装完整、配件齐全、机身无明显人为磕碰划痕，不影响二次销售。',
    shippingFeeCoverage: 'split',
    refundSla: '仓库收到退件并验收合格后，原路退款将在 1-3 个工作日内到达原支付账户。',
  },
  warranty: {
    coverageMonths: 24,
    terms: '自购买之日起提供 2 年质保。因材料或制造工艺缺陷导致的故障免费维修或换新。',
    claimProcedure: '联系在线客服或发送邮件至 support@omnilink.store，附带购买凭据与故障视频。',
    exclusions: '进水、私自拆解改装、跌落物理碎裂及不可抗力因素造成的损坏不在免费保修范围内。',
  },
  customerService: {
    operatingHours: '周一至周日 09:00 - 22:00 (UTC+8) 全年无休',
    responseSla: '在线客服 60 秒内即时响应；工单邮件 4 小时内回复',
    escalationEmail: 'escalation-vip@omnilink.store',
    supportedLanguages: ['中文 (普通话)', 'English', '日本語', 'Español'],
  },
}

// Internal Research Mock Bases & Sources
export const INTERNAL_RESEARCH_BASES: KnowledgeBaseItem[] = [
  {
    id: 'res-product-private',
    title: '产品私密研发与 BOM 文档',
    titleEn: 'Product Private Documents',
    description: '核心芯片选型、BOM 物料清单成本分解、产线良率报表与声学单元专利机密',
    descriptionEn: 'Confidential BOM cost breakdowns, chipset telemetry, patent drafts & factory test data.',
    icon: 'Lock',
    visibility: 'internal-private',
    sourceCount: 4,
    storageUsed: '19.4 MB',
    lastSynced: '2 小时前',
    activeConnections: ['Internal Deep Research Agent', 'Executive Analytics'],
    isSystem: false,
    sources: [
      {
        id: 'src-pvt-1',
        name: 'CONFIDENTIAL_BOM_Cost_Breakdown_Q3.xlsx',
        type: 'structured',
        size: '4.2 MB',
        updatedAt: '2026-08-18',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 38000,
        summary: '全组件采购单价、供应链供应商梯队对比与毛利率敏感性分析',
      },
      {
        id: 'src-pvt-2',
        name: 'Qualcomm_QCC5171_Firmware_Telemetry.pdf',
        type: 'pdf',
        size: '8.5 MB',
        updatedAt: '2026-08-16',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 52000,
        summary: '低延迟蓝牙芯片功耗曲线、发热温控阈值与 DSP 调谐日志',
      },
      {
        id: 'src-pvt-3',
        name: 'Patent_Draft_Spatial_Audio_Tracking.pdf',
        type: 'pdf',
        size: '5.1 MB',
        updatedAt: '2026-08-10',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 29000,
        summary: '空间音频六轴陀螺仪动态追踪算法在审专利权利要求书',
      },
      {
        id: 'src-pvt-4',
        name: 'Factory_Yield_Rate_Audit_Foxconn.docx',
        type: 'docx',
        size: '1.6 MB',
        updatedAt: '2026-08-19',
        visibility: 'internal-private',
        selected: false,
        tokensCount: 11000,
        summary: '代工厂第一阶段试产良品率统计与注塑模具公差改进项',
      },
    ],
  },
  {
    id: 'res-market',
    title: '行业与市场深度研报',
    titleEn: 'Market Research',
    description: '全球高端音频市场份额趋势、北美与西欧消费客群画像分析白皮书',
    descriptionEn: 'Global audio consumer trends, market share shifts & regional consumer insights.',
    icon: 'BarChart3',
    visibility: 'internal-private',
    sourceCount: 3,
    storageUsed: '14.2 MB',
    lastSynced: '1 天前',
    activeConnections: ['Internal Deep Research Agent'],
    isSystem: false,
    sources: [
      {
        id: 'src-mkt-1',
        name: 'Global_Headphone_Market_Outlook_2026.pdf',
        type: 'pdf',
        size: '6.8 MB',
        updatedAt: '2026-08-12',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 44000,
        summary: 'IDC / Canalys 2026 全球智能音频设备出货量及客单价预测',
      },
      {
        id: 'src-mkt-2',
        name: 'GenZ_Audio_Purchasing_Behavior_NorthAmerica.pdf',
        type: 'pdf',
        size: '5.4 MB',
        updatedAt: '2026-08-15',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 32000,
        summary: '北美 18-28 岁消费群体对空间音频与多设备流转的溢价支付意愿',
      },
      {
        id: 'src-mkt-3',
        name: 'Q3_Amazon_BestSeller_Rankings.csv',
        type: 'structured',
        size: '2.0 MB',
        updatedAt: '2026-08-18',
        visibility: 'internal-private',
        selected: false,
        tokensCount: 16000,
        summary: 'Amazon US 降噪耳机类目 Top 50 竞品售价波动与评论情感分析',
      },
    ],
  },
  {
    id: 'res-competitor',
    title: '竞品情报与功能对标',
    titleEn: 'Competitor Research',
    description: 'Sony WH-1000XM5 / Bose QC Ultra / Apple AirPods Max 硬件拆解与参数矩阵',
    descriptionEn: 'Hardware teardowns, spec benchmark matrices & competitive feature parity.',
    icon: 'Crosshair',
    visibility: 'internal-private',
    sourceCount: 3,
    storageUsed: '11.6 MB',
    lastSynced: '3 天前',
    activeConnections: ['Internal Deep Research Agent'],
    isSystem: false,
    sources: [
      {
        id: 'src-comp-1',
        name: 'Teardown_Bose_QC_Ultra_vs_OmniVibe.pdf',
        type: 'pdf',
        size: '7.2 MB',
        updatedAt: '2026-08-08',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 39000,
        summary: '降噪麦克风阵列拾音孔位声学腔体工程对比',
      },
      {
        id: 'src-comp-2',
        name: 'Competitor_Pricing_Strategy_Matrix_2026.xlsx',
        type: 'structured',
        size: '1.8 MB',
        updatedAt: '2026-08-14',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 14000,
        summary: '主要竞品在全球各主要站点的促销折扣节奏与渠道返点政策',
      },
      {
        id: 'src-comp-3',
        name: 'Reddit_Headphone_Community_Sentiment_Teardown.md',
        type: 'markdown',
        size: '2.6 MB',
        updatedAt: '2026-08-17',
        visibility: 'internal-private',
        selected: false,
        tokensCount: 21000,
        summary: 'r/headphones 论坛买家关于续航衰减与头梁断裂的负面口碑集中点',
      },
    ],
  },
  {
    id: 'res-compliance',
    title: '全球合规与贸易壁垒',
    titleEn: 'Compliance Research',
    description: '欧盟电池法规、CBAM 碳边境税草案、美国加州 Prop 65 法律风险预警',
    descriptionEn: 'EU Battery Directives, CBAM carbon duties & California Prop 65 compliance.',
    icon: 'Scale',
    visibility: 'internal-private',
    sourceCount: 2,
    storageUsed: '7.5 MB',
    lastSynced: '5 天前',
    activeConnections: ['Internal Deep Research Agent', 'Legal Counsel'],
    isSystem: false,
    sources: [
      {
        id: 'src-law-1',
        name: 'EU_Battery_Regulation_2026_Mandatory_Passports.pdf',
        type: 'pdf',
        size: '4.8 MB',
        updatedAt: '2026-08-01',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 28000,
        summary: '欧盟数字电池护照（Battery Passport）QR 码追溯实施细则与回收要求',
      },
      {
        id: 'src-law-2',
        name: 'California_Proposition_65_Chemical_Testing_Audit.pdf',
        type: 'pdf',
        size: '2.7 MB',
        updatedAt: '2026-08-05',
        visibility: 'internal-private',
        selected: true,
        tokensCount: 19000,
        summary: '加州 65 号提案重金属与邻苯二甲酸酯迁移量权威第三方检测报告',
      },
    ],
  },
]

export const RESEARCH_MODELS: ResearchModel[] = [
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro (Deep Research)',
    provider: 'Google DeepMind',
    badge: 'Recommended',
    description: '具备超长百万级上下文与复杂逻辑多步推理能力，擅长 cross-document 交叉比对与研报合成',
    contextWindow: '2,000,000 Tokens',
  },
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet (Hybrid Reasoning)',
    provider: 'Anthropic',
    badge: 'Reasoning',
    description: '深度思维链推演，长文本代码与工程技术标准理解极佳',
    contextWindow: '200,000 Tokens',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o (Multimodal Analysis)',
    provider: 'OpenAI',
    badge: 'Analytics',
    description: '快速多模态图表解析与结构化数值对比',
    contextWindow: '128,000 Tokens',
  },
  {
    id: 'local-airgapped',
    name: 'Local Air-gapped Llama 3 70B [V2 Preview]',
    provider: 'On-Premise Enclave',
    badge: 'V2 Preview',
    description: '企业本地私有化隔离部署，数据零出境物理隔离 (Phase 2 Roadmap)',
    contextWindow: '32,000 Tokens',
  },
]

export const MARKETPLACE_PACKAGES: MarketplacePackage[] = [
  {
    id: 'pkg-eu-trade',
    title: '欧盟跨境贸易与电商合规知识库 2026',
    titleEn: 'EU Trade & E-Commerce Compliance 2026',
    category: '法律合规',
    categoryEn: 'Legal & Compliance',
    description: '涵盖欧盟 GPSR 通用商品安全条例、EPR 环保回收注册要求、IOSS 增值税申报及 CE 认证指引。',
    descriptionEn: 'Comprehensive guide to GPSR safety directives, EPR packaging registrations, and IOSS VAT filing.',
    pricingType: 'premium',
    priceDisplay: '$89 / 季',
    sourcesCount: 14,
    downloadsCount: 1240,
    rating: 4.9,
    author: 'EuroTrade Law Partners',
    tags: ['GPSR', 'EPR', 'CE Mark', 'EU VAT'],
    badge: 'Popular',
  },
  {
    id: 'pkg-us-regulations',
    title: '美国电商税收与消费者权益规范',
    titleEn: 'US E-Commerce Regulations & State Nexus',
    category: '电商运营',
    categoryEn: 'E-Commerce Operations',
    description: '详解美国 50 州电商经济关联（Economic Nexus）、FTC 广告披露规则及 ADA 独立站无障碍合规标准。',
    descriptionEn: 'State economic nexus thresholds, FTC endorsement guidelines, and ADA website accessibility compliance.',
    pricingType: 'free',
    priceDisplay: '免费获取',
    sourcesCount: 8,
    downloadsCount: 3820,
    rating: 4.8,
    author: 'Omnilink Legal Team',
    tags: ['Sales Tax', 'FTC', 'ADA', 'US Nexus'],
    badge: 'Free',
  },
  {
    id: 'pkg-intl-shipping',
    title: '国际物流与 Incoterms 2020 履约全景图谱',
    titleEn: 'International Logistics & Incoterms Guide',
    category: '物流供应链',
    categoryEn: 'Logistics & Supply Chain',
    description: 'DDP/DAP/FOB 贸易术语权责划分、欧美关税归类（HS Code）查询技巧与跨境退运保税仓操作手册。',
    descriptionEn: 'Incoterms responsibility matrices, HS Code classification best practices, and bonded return workflows.',
    pricingType: 'premium',
    priceDisplay: '$49 / 次',
    sourcesCount: 12,
    downloadsCount: 890,
    rating: 4.7,
    author: 'Global Freight Institute',
    tags: ['Incoterms', 'DDP Logistics', 'HS Codes', 'Customs'],
    badge: 'Pro',
  },
  {
    id: 'pkg-fashion-industry',
    title: '全球时尚服饰与尺码对照标准库',
    titleEn: 'Global Fashion & Apparel Sizing Standards',
    category: '行业垂类',
    categoryEn: 'Industry Verticals',
    description: '包含中美欧日韩全球尺码转换表、国际纺织品洗涤维护标准图标集（ISO 3758）及面料质检术语。',
    descriptionEn: 'Global size conversion tables, textile care labeling standards (ISO 3758), and fabric testing terms.',
    pricingType: 'free',
    priceDisplay: '免费获取',
    sourcesCount: 6,
    downloadsCount: 4510,
    rating: 4.9,
    author: 'Textile Standard Org',
    tags: ['Size Chart', 'Care Labels', 'Apparel', 'Fabrics'],
    badge: 'Free',
  },
  {
    id: 'pkg-green-packaging',
    title: '绿色包装与可持续供应链标准 [V2]',
    titleEn: 'Green Packaging & Sustainability Standards',
    category: '可持续发展',
    categoryEn: 'Sustainability',
    description: '生物可降解材料认证（FSC / OK Compost）、碳足迹核算标准与全球可回收标识法规。',
    descriptionEn: 'Biodegradable packaging certs, carbon footprint accounting & global recycling label laws.',
    pricingType: 'coming-soon',
    priceDisplay: 'Coming Soon',
    sourcesCount: 10,
    downloadsCount: 0,
    rating: 5.0,
    author: 'EcoCommerce Alliance',
    tags: ['FSC', 'Carbon Footprint', 'Recyclable'],
    badge: 'Coming Soon',
  },
  {
    id: 'pkg-electronics-cert',
    title: '消费类电子产品全球安规准入指南 [V2]',
    titleEn: 'Consumer Electronics Global Safety & Certs',
    category: '硬件技术',
    categoryEn: 'Hardware & Tech',
    description: 'FCC / CE / UL / PSE / KC 电子产品射频与电池安全准入标准、天线增益与 SAR 辐射值检测指引。',
    descriptionEn: 'RF emissions, battery safety standards, SAR limits and multi-country test requirements.',
    pricingType: 'coming-soon',
    priceDisplay: 'Coming Soon',
    sourcesCount: 16,
    downloadsCount: 0,
    rating: 5.0,
    author: 'Global Tech Compliance Labs',
    tags: ['FCC', 'UL Safety', 'Battery UN38.3'],
    badge: 'Coming Soon',
  },
]

export const INITIAL_KNOWLEDGE_SOURCES: KnowledgeFileSource[] = [
  {
    id: 'src-prod-1',
    name: 'Acoustic_Architecture_DeepDive.pdf',
    type: 'pdf',
    size: '3.6 MB',
    sizeBytes: 3774873,
    updatedAt: '2026-08-14',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 24500,
    summary: '空间音频算法与主动降噪硬件声学架构白皮书',
  },
  {
    id: 'src-prod-2',
    name: 'Wearable_Care_Instructions_v2.md',
    type: 'markdown',
    size: '86 KB',
    sizeBytes: 88064,
    updatedAt: '2026-08-17',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 3100,
    summary: '耳垫清洁、电池保养周期与防水注意事项',
  },
  {
    id: 'src-prod-3',
    name: 'Global_Compliance_Certificates.pdf',
    type: 'pdf',
    size: '2.1 MB',
    sizeBytes: 2202009,
    updatedAt: '2026-08-12',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 12000,
    summary: 'CE, FCC, RoHS, Bluetooth SIG 官方认证编号与检测报告',
  },
  {
    id: 'src-prod-4',
    name: 'Cross_Device_Compatibility_Matrix.md',
    type: 'markdown',
    size: '145 KB',
    sizeBytes: 148480,
    updatedAt: '2026-08-18',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 5400,
    summary: 'iOS / Android / Windows / macOS 多设备无缝双连兼容性说明',
  },
  {
    id: 'src-prod-5',
    name: 'Product_Story_And_Design_Philosophy.md',
    type: 'markdown',
    size: '64 KB',
    sizeBytes: 65536,
    updatedAt: '2026-08-16',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 2800,
    summary: '极简北欧工业美学设计理念与环保可回收包装故事',
  },
  {
    id: 'src-brand-1',
    name: 'Omnilink_Brand_Guidelines_2026.pdf',
    type: 'pdf',
    size: '2.4 MB',
    sizeBytes: 2516582,
    updatedAt: '2026-08-15',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 18450,
    summary: '品牌视觉识别系统、Slogan、色盘规范与品牌调性指引',
  },
  {
    id: 'src-policy-1',
    name: 'Global_Shipping_And_Delivery_Policy_2026.md',
    type: 'markdown',
    size: '220 KB',
    sizeBytes: 225280,
    updatedAt: '2026-08-18',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 7800,
    summary: 'DHL/FedEx 跨境履约时效、偏远地区附加费与包邮门槛说明',
  },
  {
    id: 'src-policy-3',
    name: 'Warranty_Terms_2Year_Limited.pdf',
    type: 'pdf',
    size: '1.4 MB',
    sizeBytes: 1468006,
    updatedAt: '2026-08-05',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 8900,
    summary: '2 年官方有限保修责任范围、非保修意外损坏判定与售后维修网点',
  },
  {
    id: 'src-watch-1',
    name: 'OmniWatch_Titanium_Sensor_Calibration.pdf',
    type: 'pdf',
    size: '4.1 MB',
    sizeBytes: 4300000,
    updatedAt: '2026-08-15',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 15200,
    summary: '蓝宝石玻璃镜面与钛合金一体机身传感器校准指南',
  },
  {
    id: 'src-gan-1',
    name: 'OmniCharge_GaN_Safety_Thermal_Report.pdf',
    type: 'pdf',
    size: '2.8 MB',
    sizeBytes: 2936012,
    updatedAt: '2026-08-17',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 11300,
    summary: '140W 氮化镓快充温升曲线与多协议动态功率分配报告',
  },
  {
    id: 'src-prod-6',
    name: 'Troubleshooting_Diagnostic_Tree.pdf',
    type: 'pdf',
    size: '1.8 MB',
    sizeBytes: 1887436,
    updatedAt: '2026-08-11',
    visibility: 'customer-facing',
    status: 'ready',
    tokensCount: 9200,
    summary: '蓝牙配对异常与固件升级失败排障决策树',
  },
  {
    id: 'src-processing-1',
    name: 'Smart_Lens_Optics_Calibration_v3.pdf',
    type: 'pdf',
    size: '5.2 MB',
    sizeBytes: 5452595,
    updatedAt: '2026-08-20',
    visibility: 'customer-facing',
    status: 'processing',
    progress: 68,
    tokensCount: 0,
    summary: '正在进行矢量分块索引与语义特征提取 (Processing 68%)...',
  },
  {
    id: 'src-failed-1',
    name: 'Corrupted_Raw_Firmware_Dump.bin',
    type: 'txt',
    size: '8.4 MB',
    sizeBytes: 8808038,
    updatedAt: '2026-08-19',
    visibility: 'internal-private',
    status: 'failed',
    tokensCount: 0,
    errorMessage: '文件编码解析失败或格式不受支持 (Unsupported binary format)',
    summary: '解析终止：非标准纯文本结构',
  },
]

export const INITIAL_PRODUCT_BINDINGS: KnowledgeProductBinding[] = [
  {
    id: 'bind-1',
    sourceId: 'src-prod-1',
    productId: 'prod-101',
    boundAt: '2026-08-15 10:20',
    matchType: 'manual',
  },
  {
    id: 'bind-2',
    sourceId: 'src-prod-2',
    productId: 'prod-101',
    boundAt: '2026-08-17 14:15',
    matchType: 'manual',
  },
  {
    id: 'bind-3',
    sourceId: 'src-prod-2',
    productId: 'prod-102',
    boundAt: '2026-08-17 14:18',
    matchType: 'manual',
  },
  {
    id: 'bind-4',
    sourceId: 'src-prod-3',
    productId: 'prod-101',
    boundAt: '2026-08-16 09:30',
    matchType: 'manual',
  },
  {
    id: 'bind-5',
    sourceId: 'src-prod-3',
    productId: 'prod-102',
    boundAt: '2026-08-16 09:30',
    matchType: 'manual',
  },
  {
    id: 'bind-6',
    sourceId: 'src-prod-3',
    productId: 'prod-103',
    boundAt: '2026-08-16 09:30',
    matchType: 'manual',
  },
  {
    id: 'bind-7',
    sourceId: 'src-prod-4',
    productId: 'prod-101',
    boundAt: '2026-08-18 11:00',
    matchType: 'manual',
  },
  {
    id: 'bind-8',
    sourceId: 'src-prod-4',
    productId: 'prod-102',
    boundAt: '2026-08-18 11:00',
    matchType: 'manual',
  },
  {
    id: 'bind-9',
    sourceId: 'src-prod-4',
    productId: 'prod-105',
    boundAt: '2026-08-18 11:00',
    matchType: 'manual',
  },
  {
    id: 'bind-10',
    sourceId: 'src-prod-5',
    productId: 'prod-101',
    boundAt: '2026-08-16 16:45',
    matchType: 'manual',
  },
  {
    id: 'bind-11',
    sourceId: 'src-watch-1',
    productId: 'prod-102',
    boundAt: '2026-08-15 12:00',
    matchType: 'manual',
  },
  {
    id: 'bind-12',
    sourceId: 'src-gan-1',
    productId: 'prod-103',
    boundAt: '2026-08-17 15:30',
    matchType: 'manual',
  },
]

export const INITIAL_AI_SUGGESTIONS: AiSuggestedBindingMatch[] = [
  {
    id: 'sug-1',
    sourceId: 'src-prod-6',
    productId: 'prod-101',
    confidence: 0.94,
    reason: '文档内高频提及 OMNI-S1-NC 蓝牙 5.4、自适应降噪复位及固件升级指引',
    reasonEn: 'Detected high match with OMNI-S1-NC Bluetooth 5.4 ANC troubleshooting keywords',
    detectedKeywords: ['OMNI-S1-NC', '降噪耳机', 'Bluetooth 5.4', 'Reset'],
  },
  {
    id: 'sug-2',
    sourceId: 'src-prod-4',
    productId: 'prod-104',
    confidence: 0.88,
    reason: '检测到 UVC 视频免驱协议与 macOS/Windows 双系统多设备兼容性规范',
    reasonEn: 'Matched UVC protocol & multi-OS compatibility matrix for OmniLens 4K',
    detectedKeywords: ['OMNI-LENS-4K', 'macOS Sonoma', 'Windows 11', 'UVC'],
  },
]

export interface CenterKnowledgeBaseData {
  id: string
  title: string
  titleEn: string
  description: string
  descriptionEn: string
  category: string
  sourcesCount: number
  icon: string
  sources: KnowledgeSource[]
}

export const CENTER_KNOWLEDGE_BASES_DATA: CenterKnowledgeBaseData[] = [
  {
    id: 'hub-eu-reg',
    title: '欧洲贸易法规',
    titleEn: 'EU Trade Regulations',
    description: '涵盖欧盟 GPSR 通用商品安全条例、EPR 环保回收注册及 CE 认证指引。',
    descriptionEn: 'GPSR safety directives, EPR packaging registrations, and CE marking compliance.',
    category: '法律合规',
    sourcesCount: 14,
    icon: 'Scale',
    sources: [
      {
        id: 'src-eu-1',
        name: 'EU_GPSR_General_Product_Safety_2026.pdf',
        type: 'pdf',
        size: '3.8 MB',
        updatedAt: '2026-08-15',
        visibility: 'internal-private',
        selected: true,
        summary: '欧盟通用商品安全条例 GPSR 负责人与欧代合规标签最新要求',
      },
      {
        id: 'src-eu-2',
        name: 'EPR_Packaging_Recycle_Registration_Guide.pdf',
        type: 'pdf',
        size: '2.4 MB',
        updatedAt: '2026-08-10',
        visibility: 'internal-private',
        selected: true,
        summary: '德国与法国生产者延伸责任 EPR 包装法与电池回收注册细则',
      },
      {
        id: 'src-eu-3',
        name: 'CE_Marking_Directives_Summary.docx',
        type: 'docx',
        size: '1.9 MB',
        updatedAt: '2026-08-04',
        visibility: 'internal-private',
        selected: false,
        summary: '无线电设备 RED 指令与低电压 LVD 指令合规声明模板',
      },
    ],
  },
  {
    id: 'hub-logistics',
    title: '跨境物流规则',
    titleEn: 'Cross-Border Logistics',
    description: 'Incoterms 2020 国际贸易术语权责划分、欧美海关 HS Code 归类与保税仓细则。',
    descriptionEn: 'Incoterms 2020 matrices, customs HS Code classifications & bonded storage guidelines.',
    category: '供应链',
    sourcesCount: 12,
    icon: 'Truck',
    sources: [
      {
        id: 'src-log-1',
        name: 'Incoterms_2020_Trade_Terms_Rulebook.pdf',
        type: 'pdf',
        size: '4.1 MB',
        updatedAt: '2026-08-14',
        visibility: 'internal-private',
        selected: true,
        summary: 'DDP / DAP / FOB 货权转移节点与海运空运保险赔偿责任划分',
      },
      {
        id: 'src-log-2',
        name: 'US_EU_Customs_HS_Code_Classification_2026.xlsx',
        type: 'structured',
        size: '2.6 MB',
        updatedAt: '2026-08-16',
        visibility: 'internal-private',
        selected: true,
        summary: '智能消费电子与声学穿戴设备税则归类与关税税率对照表',
      },
    ],
  },
  {
    id: 'hub-market-trends',
    title: '行业趋势分析',
    titleEn: 'Market Trends & Analytics',
    description: '全球智能硬件消费趋势、北美及西欧消费者偏好与品类客单价监测。',
    descriptionEn: 'Global smart consumer device trends, pricing tolerances and brand loyalty data.',
    category: '市场研究',
    sourcesCount: 9,
    icon: 'TrendingUp',
    sources: [
      {
        id: 'src-trd-1',
        name: 'Global_Smart_Hardware_Trend_Report_2026.pdf',
        type: 'pdf',
        size: '5.5 MB',
        updatedAt: '2026-08-12',
        visibility: 'internal-private',
        selected: true,
        summary: '全球空间音频、穿戴健康监测与 AI 端侧芯片普及率调研',
      },
      {
        id: 'src-trd-2',
        name: 'North_America_Consumer_Audio_Pricing_Survey.pdf',
        type: 'pdf',
        size: '3.7 MB',
        updatedAt: '2026-08-09',
        visibility: 'internal-private',
        selected: false,
        summary: '北美高净值客群对高端降噪耳机的价格敏感度与复购周期分析',
      },
    ],
  },
  {
    id: 'hub-electronics-safety',
    title: '全球消费电子安规',
    titleEn: 'Global Safety Standards',
    description: 'FCC / CE / UL / PSE 电子产品射频与锂电池 UN38.3 安全准入测试标准。',
    descriptionEn: 'Safety and compliance certifications across FCC, CE, UL and battery standards.',
    category: '技术标准',
    sourcesCount: 16,
    icon: 'ShieldCheck',
    sources: [
      {
        id: 'src-saf-1',
        name: 'FCC_CE_UL_Safety_Standards_Overview.pdf',
        type: 'pdf',
        size: '4.6 MB',
        updatedAt: '2026-08-11',
        visibility: 'internal-private',
        selected: true,
        summary: '全球主要市场电子电气产品 EMC 电磁兼容与安规认证流程',
      },
      {
        id: 'src-saf-2',
        name: 'UN38.3_Lithium_Battery_Transport_Testing.pdf',
        type: 'pdf',
        size: '3.1 MB',
        updatedAt: '2026-08-07',
        visibility: 'internal-private',
        selected: true,
        summary: '锂电航空海运运输鉴定书与跌落、挤压安全测试规范',
      },
    ],
  },
  {
    id: 'hub-trade-contract',
    title: '国际商事仲裁与合同标准',
    titleEn: 'International Trade Contracts',
    description: '跨境供货协议示范文本、不可抗力条款及国际商事仲裁管辖权指引。',
    descriptionEn: 'Standard model contracts, force majeure clauses and cross-border dispute guidelines.',
    category: '法律合规',
    sourcesCount: 8,
    icon: 'FileCheck2',
    sources: [
      {
        id: 'src-ctr-1',
        name: 'International_Supply_Agreement_Model.docx',
        type: 'docx',
        size: '1.8 MB',
        updatedAt: '2026-08-03',
        visibility: 'internal-private',
        selected: true,
        summary: '包含质保期追偿、知识产权免责及排他性销售的中英文示范合同',
      },
    ],
  },
  {
    id: 'hub-green-package',
    title: '绿色包装与环保规范',
    titleEn: 'Eco Packaging Standards',
    description: '生物可降解材料认证、FSC 环保森林认证及全球碳足迹合规要求。',
    descriptionEn: 'Biodegradable material standards, FSC forest certificates and ESG requirements.',
    category: '环保标准',
    sourcesCount: 10,
    icon: 'Leaf',
    sources: [
      {
        id: 'src-grn-1',
        name: 'FSC_Certified_Paper_Packaging_Guidelines.pdf',
        type: 'pdf',
        size: '2.9 MB',
        updatedAt: '2026-08-06',
        visibility: 'internal-private',
        selected: true,
        summary: 'FSC-COC 产销监管链认证与大豆油墨印刷环保标识规范',
      },
    ],
  },
]

export interface AiResearchModelOption {
  id: string
  name: string
  tag: string
  description: string
}

export const AI_RESEARCH_MODELS_DATA: AiResearchModelOption[] = [
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    tag: '深度研报',
    description: '支持超长跨文档联合推理与研报合成，逻辑严密',
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    tag: '极速响应',
    description: '轻量秒级检索与关键信息快速定位',
  },
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet',
    tag: '长文研究',
    description: '深度思维链分析，适合复杂大纲与多章节撰写',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    tag: '深度思考',
    description: '针对复杂算法、物料成本及严密逻辑推理优化',
  },
]

