// DEFERRED (Demo #56 · P4/P9): legacy semantic dashboard page.
// Depends on product_semantics / semantic_schemas that were NEVER created in the
// live DB. Not part of the Demo storefront/agent flow.
// Semantic Source of Truth = products.semantic_data.
import { getProductById } from '@/lib/products/service'
import { createClientServer } from '@/lib/supabase/server'
import Link from 'next/link'
import { notFound } from 'next/navigation'

export default async function ProductSemanticPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  const product = await getProductById(id).catch(() => null)

  if (!product) {
    notFound()
  }

  const supabase = await createClientServer()

  const { data: semantics } = await supabase
    .from('product_semantics')
    .select(`
      *,
      semantic_schemas(*)
    `)
    .eq('product_id', id)
    .maybeSingle()

  const rawData = product.raw_data as Record<string, unknown> | null

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <Link
            href={`/dashboard/products/${id}/edit`}
            className="text-iris hover:text-iris text-sm"
          >
            ← Back to Product
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mt-4">Product Semantic Data</h1>
          <p className="text-gray-600 mt-1">{product.name}</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Stable Core */}
          <div className="bg-white rounded-md shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Stable Core</h2>
            <div className="space-y-3">
              <div className="flex justify-between py-2 border-b">
                <span className="text-gray-600">SKU</span>
                <span className="font-medium">{product.sku || 'N/A'}</span>
              </div>
              <div className="flex justify-between py-2 border-b">
                <span className="text-gray-600">Price</span>
                <span className="font-medium">{product.price} {product.currency}</span>
              </div>
              <div className="flex justify-between py-2 border-b">
                <span className="text-gray-600">Inventory</span>
                <span className="font-medium">{product.inventory}</span>
              </div>
              <div className="flex justify-between py-2 border-b">
                <span className="text-gray-600">Status</span>
                <span className="font-medium">{product.status}</span>
              </div>
              <div className="py-2">
                <span className="text-gray-600 block mb-1">Description</span>
                <span className="font-medium">{product.description || 'N/A'}</span>
              </div>
            </div>
          </div>

          {/* Raw Data */}
          <div className="bg-white rounded-md shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Raw Data</h2>
            {rawData ? (
              <div className="space-y-2 max-h-80 overflow-y-auto">
                {Object.entries(rawData).map(([key, value]) => (
                  <div key={key} className="flex justify-between py-2 border-b">
                    <span className="text-gray-600">{key}</span>
                    <span className="font-medium text-sm max-w-xs truncate">
                      {String(value)}
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-500">No raw data available</p>
            )}
          </div>

          {/* Semantic Data */}
          <div className="bg-white rounded-md shadow-lg p-6 lg:col-span-2">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Semantic Data</h2>
            {semantics ? (
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                  <div className="bg-iris rounded-lg p-4">
                    <span className="text-sm text-gray-600">Schema</span>
                    <p className="font-medium mt-1">
                      {semantics.semantic_schemas?.industry || 'Unknown'} v{semantics.semantic_schemas?.version || '1.0'}
                    </p>
                  </div>
                  <div className="bg-apricot rounded-lg p-4">
                    <span className="text-sm text-gray-600">Confidence</span>
                    <p className="font-medium mt-1">{(semantics.confidence * 100).toFixed(0)}%</p>
                  </div>
                  <div className="bg-iris rounded-lg p-4">
                    <span className="text-sm text-gray-600">Generated By</span>
                    <p className="font-medium mt-1">{semantics.generated_by}</p>
                  </div>
                </div>

                <div className="border rounded-lg overflow-hidden">
                  <table className="min-w-full">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Field
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Value
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Source
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Confidence
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {Object.entries(semantics.semantic_data as Record<string, unknown>).map(([key, value]) => (
                        <tr key={key}>
                          <td className="px-4 py-3 whitespace-nowrap">
                            <span className="font-medium text-gray-900">{key}</span>
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap">
                            <span className="text-gray-700">{String(value)}</span>
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap">
                            <span className="text-sm text-iris">Raw Data</span>
                          </td>
                          <td className="px-4 py-3 whitespace-nowrap">
                            <span className="text-sm text-apricot">{(semantics.confidence * 100).toFixed(0)}%</span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="text-sm text-gray-500">
                  <p>Last updated: {new Date(semantics.updated_at).toLocaleString()}</p>
                </div>
              </div>
            ) : (
              <div className="text-center py-8">
                <p className="text-gray-500 mb-4">No semantic data available for this product</p>
                <button
                  onClick={async () => {
                    await fetch(`/api/products/${id}`, { method: 'POST' })
                    window.location.reload()
                  }}
                  className="bg-iris text-white px-4 py-2 rounded-lg hover:bg-iris"
                >
                  Generate Semantic Data
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
