-- ============================================================================
-- Migration: 20260826_000001_atomic_product_create.sql
--
-- Purpose: Provide a single DB-level transaction for creating a product together
-- with its options and variants, so the merchant "create product" flow is atomic
-- and can never leave orphan rows (product without options/variants, or a
-- half-written variant set) on a mid-flow failure.
--
-- Security model (must NOT weaken the 99c8337 ownership boundary):
--   * SECURITY INVOKER (the default). The function executes with the privileges
--     of the calling authenticated merchant. RLS on products / product_options /
--     product_variants therefore STILL APPLIES during every INSERT.
--     - products  : policy requires store_id IN (stores WHERE owner_id = auth.uid())
--     - options   : policy requires product_id owned by auth.uid() (via store chain)
--     - variants  : policy requires product_id owned by auth.uid() (via store chain)
--     Because the product row is inserted first (same transaction), the subsequent
--     option/variant inserts are visible to RLS and pass ownership checks.
--     A caller passing a store_id they do not own is RLS-denied — ownership is
--     enforced by the database, not by trusting request input.
--   * The function ONLY inserts rows. It never reads SERVICE_ROLE_ONLY tables
--     (semantic_schemas / semantic_fields / product_semantics / ...), never uses
--     the service role, and never bypasses requireUser()/ownsProduct().
--   * EXECUTE is granted to `authenticated` ONLY (revoked from PUBLIC/anon), so
--     the endpoint remains auth-gated at the DB layer as well.
--
-- Conventions:
--   * No DROP / TRUNCATE / CASCADE on existing data. Idempotent via
--     CREATE OR REPLACE FUNCTION.
--   * JSONB parameters carry pre-validated option/variant payloads produced by
--     the application layer (which keeps the tested combination/SKU logic).
--
-- Rollback: 20260826_000002_rollback_atomic_product_create.sql
-- ============================================================================

-- ============================================================================
-- 1. Atomic create-product function
-- ============================================================================
CREATE OR REPLACE FUNCTION create_product_atomic(
  p_store_id uuid,
  p_product jsonb,
  p_options jsonb DEFAULT '[]'::jsonb,
  p_variants jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_product_id uuid;
  v_option jsonb;
  v_variant jsonb;
  v_option_idx int := 0;
  v_options_count int := 0;
  v_variants_count int := 0;
BEGIN
  -- --------------------------------------------------------------------------
  -- 1) Insert the product. RLS (INVOKER) enforces store ownership here; a
  --    non-owned store_id is rejected before any row is written.
  -- --------------------------------------------------------------------------
  INSERT INTO products (
    store_id,
    name,
    sku,
    price,
    currency,
    inventory,
    description,
    status,
    raw_data
  ) VALUES (
    p_store_id,
    p_product->>'name',
    NULLIF(p_product->>'sku', ''),
    COALESCE((p_product->>'price')::numeric, 0),
    COALESCE(p_product->>'currency', 'USD'),
    COALESCE((p_product->>'inventory')::int, 0),
    NULLIF(p_product->>'description', ''),
    COALESCE(p_product->>'status', 'draft'),
    COALESCE(p_product->'raw_data', '{}'::jsonb)
  )
  RETURNING id INTO v_product_id;

  -- --------------------------------------------------------------------------
  -- 2) Insert options (position = insertion order).
  -- --------------------------------------------------------------------------
  FOR v_option IN SELECT * FROM jsonb_array_elements(p_options)
  LOOP
    INSERT INTO product_options (
      product_id,
      name,
      code,
      values,
      position
    ) VALUES (
      v_product_id,
      v_option->>'name',
      v_option->>'code',
      COALESCE(v_option->'values', '[]'::jsonb),
      v_option_idx
    );
    v_option_idx := v_option_idx + 1;
    v_options_count := v_options_count + 1;
  END LOOP;

  -- --------------------------------------------------------------------------
  -- 3) Insert variants (generated by the application layer).
  -- --------------------------------------------------------------------------
  FOR v_variant IN SELECT * FROM jsonb_array_elements(p_variants)
  LOOP
    INSERT INTO product_variants (
      product_id,
      sku,
      price,
      currency,
      inventory,
      status,
      option_values
    ) VALUES (
      v_product_id,
      NULLIF(v_variant->>'sku', ''),
      NULLIF(v_variant->>'price', '')::numeric,
      COALESCE(v_variant->>'currency', 'USD'),
      NULLIF(v_variant->>'inventory', '')::int,
      COALESCE(v_variant->>'status', 'draft'),
      COALESCE(v_variant->'option_values', '{}'::jsonb)
    );
    v_variants_count := v_variants_count + 1;
  END LOOP;

  -- Entire body runs inside one transaction; if any INSERT raises, Postgres
  -- rolls back ALL inserted rows automatically. No partial state is possible.
  RETURN jsonb_build_object(
    'success', true,
    'product_id', v_product_id,
    'options_created', v_options_count,
    'variants_created', v_variants_count
  );
END;
$$;

COMMENT ON FUNCTION create_product_atomic(uuid, jsonb, jsonb, jsonb) IS
  'Atomically create a product with its options and variants in a single DB transaction. SECURITY INVOKER: RLS ownership enforced. EXECUTE restricted to authenticated.';

-- ============================================================================
-- 2. Lock down EXECUTE to authenticated merchants only (auth-gated at DB layer)
-- ============================================================================
REVOKE EXECUTE ON FUNCTION create_product_atomic(uuid, jsonb, jsonb, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_product_atomic(uuid, jsonb, jsonb, jsonb) FROM anon;
GRANT EXECUTE ON FUNCTION create_product_atomic(uuid, jsonb, jsonb, jsonb) TO authenticated;

-- ============================================================================
-- End of migration 20260826_000001_atomic_product_create.sql
-- ============================================================================
